micronaut:
  application:
    name: carros532

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/grpc
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true